# Generated by Django 2.1 on 2020-04-04 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('gstin', models.CharField(max_length=15, verbose_name='GST Number')),
                ('aadhar_no', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Aadhar Number')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('mobile_number', models.BigIntegerField()),
                ('static_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
