# Generated by Django 2.1 on 2020-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
