# Generated by Django 2.1 on 2020-04-04 07:44

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to=registration.models.document_directory_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='otp',
            name='profile',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
