# Generated by Django 2.1 on 2020-04-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200404_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tax', models.BigIntegerField()),
                ('tax_paid', models.BigIntegerField()),
                ('total_income', models.BigIntegerField()),
                ('loss', models.BigIntegerField()),
                ('deemed_income', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gstin',
        ),
        migrations.AddField(
            model_name='profile',
            name='aid',
            field=models.BigIntegerField(default=102025112, primary_key=True, serialize=False, verbose_name='AID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_number',
            field=models.CharField(default='AGS241512', max_length=15, verbose_name='PAN Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itrdataset',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
    ]
