# Generated by Django 2.1 on 2020-04-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200410_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(max_length=50, verbose_name='District'),
        ),
    ]
