# Generated by Django 2.1 on 2020-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20200410_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', max_length=20),
        ),
    ]
