# Generated by Django 2.1 on 2020-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20200410_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='itrdataset',
            name='reported_loss',
            field=models.BigIntegerField(default=0),
        ),
    ]
