# Generated by Django 2.1 on 2020-04-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_itrdataset_reported_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itrdataset',
            name='reported_loss',
        ),
    ]
